name: Go

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: "Build and Test"
    strategy:
      matrix:
        go-version: [1.24.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false

      - name: Coverage
        run: go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out
